# Generated by Django 6.0 on 2025-12-26 18:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('logo', models.URLField()),
                ('address', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('date_created', models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 18, 16, 21, 639562))),
            ],
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('prefered_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('dob', models.DateField()),
                ('date_created', models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 18, 16, 21, 640563))),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('prefered_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('dob', models.DateField()),
                ('type', models.CharField(choices=[('EXTERNAL', 'External'), ('VOLUNTEER', 'Volunteer'), ('ORGANISER', 'Organiser')], max_length=30)),
                ('medical_info', models.CharField(max_length=500)),
                ('dietary_requirements', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 18, 16, 21, 640563))),
            ],
        ),
        migrations.CreateModel(
            name='waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('date_signed', models.DateTimeField()),
                ('photo_consent', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 18, 16, 21, 640563))),
            ],
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField()),
                ('date_created', models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 18, 16, 21, 639562))),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.event')),
            ],
        ),
        migrations.CreateModel(
            name='attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('prefered_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('dob', models.DateField()),
                ('medical_info', models.CharField(max_length=500)),
                ('dietary_requirements', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 18, 16, 21, 640563))),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.parent')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('cover_image', models.URLField()),
                ('repo_link', models.URLField()),
                ('playable_link', models.URLField()),
                ('date_created', models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 18, 16, 21, 640563))),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.event')),
            ],
        ),
        migrations.CreateModel(
            name='attendee_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SIGNED_UP', 'Signed Up'), ('CHECKED_IN', 'Checked in'), ('SCANNED_IN', 'Scanned In')], default='SIGNED_UP')),
                ('date_created', models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 18, 16, 21, 641563))),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.attendee', unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.project')),
                ('waiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.waiver')),
            ],
        ),
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_type', models.CharField(choices=[('STAFF_LOGIN', 'Staff Login'), ('ATTENDEE_LOGIN', 'Attendee Login')])),
                ('token', models.CharField(max_length=500)),
                ('expiry', models.IntegerField()),
                ('date_created', models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 18, 16, 21, 641563))),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.attendee')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.staff')),
            ],
        ),
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 18, 16, 21, 641563))),
                ('attendee_signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.attendee_signup', unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.project')),
            ],
        ),
        migrations.CreateModel(
            name='staff_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_description', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 18, 16, 21, 640563))),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.event')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.staff', unique=True)),
                ('waiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.waiver')),
            ],
        ),
    ]
