# Generated by Django 6.0 on 2025-12-26 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_attendee_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 20, 8, 43, 474008, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attendee_signup',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 20, 8, 43, 474008, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 20, 8, 43, 473007, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 20, 8, 43, 473007, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 20, 8, 43, 475007, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='parent',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 20, 8, 43, 474008, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 20, 8, 43, 474008, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 20, 8, 43, 473007, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='staff_signup',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 20, 8, 43, 474008, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 20, 8, 43, 475007, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 20, 8, 43, 474008, tzinfo=datetime.timezone.utc)),
        ),
    ]
