# Generated by Django 6.0 on 2025-12-26 23:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_alter_attendee_date_created_alter_attendee_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 23, 7, 32, 226910, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.parent'),
        ),
        migrations.AlterField(
            model_name='attendee_signup',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 23, 7, 32, 227910, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attendee_signup',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.project'),
        ),
        migrations.AlterField(
            model_name='attendee_signup',
            name='waiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.waiver'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 23, 7, 32, 225906, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 23, 7, 32, 225906, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.attendee'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 23, 7, 32, 227910, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.staff'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 23, 7, 32, 226910, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 23, 7, 32, 226910, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 23, 7, 32, 226910, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='staff_signup',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 23, 7, 32, 226910, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='staff_signup',
            name='waiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.waiver'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 23, 7, 32, 227910, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 12, 26, 23, 7, 32, 226910, tzinfo=datetime.timezone.utc)),
        ),
    ]
