# Generated by Django 6.0.2 on 2026-02-22 14:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_alter_attendee_date_created_alter_attendee_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2026, 2, 22, 14, 0, 46, 490340, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attendee_signup',
            name='attendee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testing.attendee'),
        ),
        migrations.AlterField(
            model_name='attendee_signup',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2026, 2, 22, 14, 0, 46, 490340, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2026, 2, 22, 14, 0, 46, 489332, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2026, 2, 22, 14, 0, 46, 488333, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2026, 2, 22, 14, 0, 46, 491344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='parent',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2026, 2, 22, 14, 0, 46, 490340, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2026, 2, 22, 14, 0, 46, 490340, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2026, 2, 22, 14, 0, 46, 489332, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='staff_signup',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2026, 2, 22, 14, 0, 46, 489835, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='staff_signup',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testing.staff'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='attendee_signup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testing.attendee_signup'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2026, 2, 22, 14, 0, 46, 490340, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2026, 2, 22, 14, 0, 46, 489835, tzinfo=datetime.timezone.utc)),
        ),
    ]
